name: Build Python 3.12.13 for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Download Source
      run: |
        curl -O https://www.python.org/ftp/python/3.12.13/Python-3.12.13.tgz
        tar -xzf Python-3.12.13.tgz

    - name: Get Externals
      run: |
        cd Python-3.12.13/PCbuild
        ./get_externals.bat

    - name: Build
      run: |
        cd Python-3.12.13/PCbuild
        ./build.bat -c Release -p x64

    - name: Collect Files
      run: |
        mkdir Python-3.12.13-Full
        
        # 复制可执行文件和dll
        copy Python-3.12.13\PCbuild\amd64\*.exe Python-3.12.13-Full\
        copy Python-3.12.13\PCbuild\amd64\*.dll Python-3.12.13-Full\
        copy Python-3.12.13\PCbuild\amd64\*.pyd Python-3.12.13-Full\
        copy Python-3.12.13\PCbuild\amd64\LICENSE.txt Python-3.12.13-Full\
        
        # 复制标准库
        xcopy Python-3.12.13\Lib Python-3.12.13-Full\Lib\ /E /I /Q
        
        # 复制 tcl/tk 支持
        xcopy Python-3.12.13\PCbuild\amd64\tcl86t.dll Python-3.12.13-Full\ /Y
        xcopy Python-3.12.13\PCbuild\amd64\tk86t.dll Python-3.12.13-Full\ /Y

    - name: Install pip
      run: |
        Python-3.12.13-Full\python.exe -m ensurepip
        Python-3.12.13-Full\python.exe -m pip install --upgrade pip

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Python-3.12.13-Full
        path: Python-3.12.13-Full/
